### ISSUE TITLE
dynamic_template_data is not being passed to email template

### ISSUE THREAD

**Issue by sebscholl** [sendgrid/sendgrid-nodejs#1094] opened 2020-04-15 22:30 UTC
### Issue Summary
When using the @sendgrid/mail client for Node, I'm unable to pass dynamic_template_data to my email templates. Additionally, I'm unable to find documentation around how to successfully accomplish this.

### Code Snippet
```node
  sgMail.setApiKey(SENDGRID_API_KEY);

  await sgMail.send({
    to: "some@one.com",
    from: 'my@email',
    templateId: "EMAIL_TEMPLATE_ID",
    dynamic_template_data: {
      variable1,
      variable2
    },
  });
```

### Technical details:
* sendgrid-nodejs version: ^6.5.5
* node version: 10.16.0

**Comment by eshanholtz** [comment] 2020-04-17 22:15
Hi @sebscholl,
I wasn't able to recreate the issue. I followed the basic example outlined in the [use case guide](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/transactional-templates.md) and was able to successfully send an email. Looking at your code snippet, it's possible the issue is with the way you're passing template data. You should be passing in key-value pairs for your variables.

**Comment by millerm** [comment] 2020-04-20 14:56
@sebscholl would you mind posting a snippet of your handlebars code? I had a similar issue and it turned out that I was iterating through an array that wasn't present in the JSON payload so it broke the whole template.

Example:
```
{{#if items.length}}
  <ul>
    {{#each items as |thing|}}
      <li>{{thing.title}}</li>
    {{/each}}
  </ul>
{{/if}}
```

items was undefined so obviously it didn't have `.length` as a property and the whole email went kaput.

**Comment by sebscholl** [comment] 2020-04-20 15:11
Hey there!

Here is an example of my template:

```text
You've been assigned to {{ticketType}} #{{ticketNumber}} on the {{projectName}} project.

You can see the latest progress here:

https://app.projectz.com/{{projectSlug}}/{{ticketType}}s/{{ticketId}}
```

@eshanholtz - the syntax I'm using creates a key/value object using the variable name and value. For example:

```js
let variable1 = "value"

const myObj = { variable1 }

console.log(myObj)

=> { variable1: "value" }
```

**Comment by eshanholtz** [comment] 2020-04-22 19:07
Hey @sebscholl 

I still have not been able to recreate this issue with sendgrid-node v6.5.5 or latest. Here is the exact code I used:

template:
```html
<html>
<head>
</head>
<body>
You've been assigned to {{ticketType}} #{{ticketNumber}} on the {{projectName}} project.

You can see the latest progress here:

https://app.projectz.com/{{projectSlug}}/{{ticketType}}s/{{ticketId}}
</body>
</html>
```
node:
```javascript
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const projectSlug = 'foo';
const projectName = 'Project Foo';
const ticketNumber = 1234;
const ticketId = 'ID' + String(ticketNumber);

const msg = {
  personalizations: [{
    to: [{
      email: 'my@email.com',
      name: 'myself',
    }],
  }],
  from: {
    email: 'my@email.com',
    name: 'myself',
  },
  templateId: 'd-0123456789abcdef0123456789abcdef',
  dynamic_template_data: {
    ticketNumber,
    ticketId,
    projectSlug,
    projectName,
    ticketType: 'bar',
  },
};
sgMail.send(msg).then(([response, body]) => {
  console.log(response.statusCode);
  console.log(body);
}).catch(err => console.log(err));
```

And I received an email with this body:
```text
You've been assigned to bar #1234 on the Project Foo project. You can see the latest progress here: https://app.projectz.com/foo/bars/ID1234  
```

Are you getting a 200 OK response and actually receiving the email, just without handlebar variables replaced? If not, do you see your emails in [your recent activity](https://app.sendgrid.com/email_activity)?

**Comment by sebscholl** [comment] 2020-04-23 20:59
Thank you!

**Comment by eshanholtz** [comment] 2020-04-28 16:06
Hey @sebscholl I'm going to go ahead and close this issue since it sounds like your problem was resolved. Feel free to reopen if you need more help

**Closed by eshanholtz** 2020-04-28 16:06 UTC
Labels: status: waiting for feedback, type: question
