### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unauthorized (401) Maximum credits exceeded

### ISSUE THREAD

**Issue by LiubaB** [sendgrid/sendgrid-nodejs#1032] opened 2020-01-23 12:32 UTC
I integrated sendGrid and everything worked fine, but now I receive the following error message below every time I try to send emails. 
Although my limit was not exceeded (only 102 emails were sent this month, and a limit is 100 emails per day)

```
(node:2233) UnhandledPromiseRejectionWarning: Unauthorized (401)
  Maximum credits exceeded
    null
    null
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:2233) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2233) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### The following code is used to send the email:
```
const sgMail = require('@sendgrid/mail');
const { SENDGRID_API_KEY } = process.env;

const forgotPasswordMail = (to, first_name, last_name) => {
  sgMail.setApiKey(SENDGRID_API_KEY);
  const msg = {
    to,
    from: 'support@support.com',
    subject: 'Your password reset request',
    templateId: 'd-71746df705c44a8b9d5bb5c10d861754',
    dynamic_template_data: {
      first_name,
      last_name,
    }
  };
  sgMail.send(msg);
}

```
## Technical details:
* node version: v10.15.3

**Comment by childish-sambino** [comment] 2020-02-24 17:24
Closing as duplicate of #970 

See my [comment](https://github.com/sendgrid/sendgrid-nodejs/issues/970#issuecomment-590447667) there to follow-up.

**Closed by childish-sambino** 2020-02-24 17:24 UTC

**Comment by sanmithapalanisamy** [comment] 2021-07-30 07:45
Facing the same issue. Per day limit is also not reached but I receiving 

ResponseError: Unauthorized
    at node_modules/@sendgrid/client/src/classes/client.js:146:29
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 401,
  response: {
    headers: {
      server: 'nginx',
      date: 'Fri, 30 Jul 2021 07:43:50 GMT',
      'content-type': 'application/json',
      'content-length': '76',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html',
      'strict-transport-security': 'max-age=600; includeSubDomains'
    },
    body: { errors: [Array] }
  }
} {
  errors: [ { message: 'Maximum credits exceeded', field: null, help: null } ]
}

**Comment by JenniferMah** [comment] 2021-07-30 18:50
Hi @sanmithapalanisamy! SendGrid Support has the tools to help debug these kinds of issues. Please open a [new support ticket](https://support.sendgrid.com/hc/en-us) to get help with this 401 error.

**Comment by chmsajid7** [comment] 2021-09-23 07:24
I am facing the same issue: {"errors":[{"message":"Maximum credits exceeded","field":null,"help":null}]}

Any kind of help will be appreciated.
Thanks!
