### ISSUE TITLE
Add/Update Badges on README

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#516] opened 2017-10-20 22:20 UTC
Similar to what was done on [the SendGrid node README](https://github.com/sendgrid/sendgrid-nodejs/pull/486):
- put the logo at the top of the list
- make sure the other badges are available like so:
```
![SendGrid Logo](https://uiux.s3.amazonaws.com/2016-logos/email-logo%402x.png)
```
For the following, make sure the correct repo is linked!
For email notifications, you can change the "nodejs" to the language of this repo (e.g. java, python, ruby, php, csharp, go, etc)

```
[![BuildStatus](https://travis-ci.org/sendgrid/sendgrid-nodejs.svg?branch=master)](https://travis-ci.org/sendgrid/sendgrid-nodejs)
[![Email Notifications Badge](https://dx.sendgrid.com/badge/nodejs)](https://dx.sendgrid.com/newsletter/nodejs)
[![npm](https://img.shields.io/npm/l/express.svg)]()
[![Twitter Follow](https://img.shields.io/twitter/follow/sendgrid.svg?style=social&label=Follow)](https://twitter.com/sendgrid)
[![GitHub contributors](https://img.shields.io/github/contributors/sendgrid/sendgrid-nodejs.svg)](https://github.com/sendgrid/sendgrid-nodejs/graphs/contributors)
```

Thank you and happy #Hacktoberfest!!

**Comment by mbernier** [comment] 2017-10-20 22:21
Duplicate of #486

**Closed by mbernier** 2017-10-20 22:21 UTC
Labels: status: duplicate
