### ISSUE TITLE
Substitution is not working

### ISSUE THREAD

**Issue by sydneyhenrard** [sendgrid/sendgrid-nodejs#441] opened 2017-09-07 14:54 UTC
#### Issue Summary

I migrated from `sendgrid 2.0.0` to `@sendgrid/mail 6.1.2`, the substitutions are not working anymore

#### Steps to Reproduce

```
SendgridService.prototype.sendTestEmail = function () {
  var text = 'Hi %DISPLAY_NAME%\n\n'
  const msg = {
    to: 'xxx@gmail.com',
    subject: 'Test Email',
    from: {email: 'no-reply@example.com', name: 'Test'},
    text: text,
    substitutions: {
      "%DISPLAY_NAME%": 'Test'
    }
  }
  return sendgrid.send(msg)
}
```

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 8.4.0

**Comment by thinkingserious** [comment] 2017-09-07 16:10
Hello @sydneyhenrard,

[Here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional_templates) is a complete example.

It appears that you need to set the `substitutionWrappers`. In your case that would be `%`. Then in the `substitutions` object, you would leave the `%` characters out.

With Best Regards,

Elmer

**Comment by sydneyhenrard** [comment] 2017-09-07 16:36
Is there a convention on variable?

```
SendgridService.prototype.sendTestEmail = function () {
  var text = 'Hi %DISPLAY_NAME% - %displayname%\n\n'
  const msg = {
    to: 'xxx@gmail.com',
    subject: 'Test Email',
    from: {email: 'no-reply@example.com', name: 'Test'},
    text: text,
    substitutionWrappers: ['%', '%'],
    substitutions: {
      DISPLAY_NAME: 'Test',
      displayname: 'Test'
    }
  }
  return sendgrid.send(msg)
}
```

The received email:

```
Hi %DISPLAY_NAME% – Test
```

**Comment by thinkingserious** [comment] 2017-09-08 19:51
Hello @sydneyhenrard,

I was able to reproduce this issue. I have added this to our backlog for a fix.

With Best Regards,

Elmer

**Comment by adamreisnz** [comment] 2017-09-11 02:39
@thinkingserious is this on your end or an issue with the Node SDK?

**Comment by thinkingserious** [comment] 2017-09-11 03:12
It's an issue with the SDK. I'm not quite sure exactly what the issue is though. I plan to examine the payload to help troubleshoot.

**Comment by sydneyhenrard** [comment] 2017-09-11 05:14
If I use camelCase variable, I have no problem with the substitutions even for substitution 0

**Comment by thinkingserious** [comment] 2017-09-11 21:17
Thanks @sydneyhenrard,

That should help get to the root cause quicker :)

**Comment by adamreisnz** [comment] 2017-09-11 22:25
I think I may know what the problem is, let me investigate.

**Comment by adamreisnz** [comment] 2017-09-11 22:58
#442 should fix this 👍

**Comment by thinkingserious** [comment] 2017-09-12 04:30
Merged as v6.1.3, thanks @adamreisnz!

**Comment by thinkingserious** [comment] 2017-09-12 04:32
@sydneyhenrard,

For helping us solve this issue, we would like to [send you some swag](https://dx.sendgrid.com/swag) as a token of our gratitude.

Thanks for supporting SendGrid!

With Best Regards,

Elmer

**Closed** 2017-10-01 04:48 UTC
Labels: status: help wanted, type: question

**Comment by greglbyv** [comment] 2018-01-11 01:51
had the same problem in 01/2018.  changed our substitution variables from %companyname% to %company_name% because single word variables were not working.  fixed immediately.

**Comment by thinkingserious** [comment] 2018-01-11 18:25
Hi @greglbyv,

What version of the SDK are you using? Thanks!

With Best Regards,

Elmer

**Comment by airstofather** [comment] 2018-06-01 13:34
Are substitutions supposed to work when using design built template? I can get them working only when I build the template by hand, the ones built with the design tool never work.

**Comment by thinkingserious** [comment] 2018-06-05 01:35
@airstofather,

To help you out I will need further detail. 1) Which template are you referring to? 2) Could you provide sample code? Both the template HTML and the Node.js code. Thank you!

Also, it might be best to open a separate issue. Thanks!

With Best Regards,

Elmer

**Comment by airstofather** [comment] 2018-06-05 13:40
@thinkingserious 

Please ignore my previous comment. After your reply I went back to look at it with fresh eyes and it was an extra space in the interpolated variable that was causing the issue which I didn't catch the first time.

All is working as advertised. Thank you.

**Comment by jay8t6** [comment] 2019-03-25 14:45
@thinkingserious I have tried everything, camelcase, underscore. The variable still would not populate, when I do the testing via the sendgrid UI and pass in the variable, it works fine. It just wouldnt work through firebase cloud functions. Here's my code

`const msgbody = {
          to: userData.email,
          from: 'auto-reply@somedomain.com',
          subject: 'Registration Complete',
          templateId: 'd-dffc1e7c8a4a4ed5a4384eded1701f65',
          substitutionWrappers: ['{{', '}}'],
          substitutions: {
            first_name: userData.firstName
          }
        }`
