### ISSUE TITLE
Content-Type (and other) headers.

### ISSUE THREAD

**Issue by souluniversal** [sendgrid/sendgrid-nodejs#153] opened 2015-01-23 00:42 UTC
For the life of me, no matter what approach I try, I cannot get the Content-Type header set appropriately.... I get two Content-Type headers. I have tried.. email.headers, email.setHeaders.. etc... Who knows the deal? Thank you!

Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: Darth Vader <darthvader@arturito.net>
To: rtaylor@scholarlab.com, rdtaylor.atl@gmail.com
Subject: Millennium Falcon
Content-Type: text/calendar
Content-Disposition: inline;charset=utf-8
Message-ID: <14b13df44de.4c5.141146@ismtpd-024>
Date: Thu, 22 Jan 2015 22:59:35 +0000 (UTC)
X-SG-EID: jaENuOTdB8Bk7RtuiCyqc+0Jw9hn9vZMXQqZgO3H2d8ZuYj1STs3m+NtDr5mindwuuF7qsxYYEOGBj
 wLE4Z+oGVEFRW0pXXaOiDm/DbEnZPds49E4TT+FZq6TW0PIxIhs/b/mISCWGnhjHcrU1PUvpVCIV3q
 O7/I5Jfo0RftrOwc3fr2+ZJSFvGuWVyQiIYv
X-Feedback-ID: 1524223:IY3rkXZ8NBJgzRvJtFVqQ6lJGwFckyQOu1koyu0IaYs=:IY3rkXZ8NBJgzRvJtFVqQ6lJGwFckyQOu1koyu0IaYs=:SG

**Comment by eddiezane** [comment] 2015-01-24 03:57
Duplicate of #154

**Closed by eddiezane** 2015-01-24 03:57 UTC
