### ISSUE TITLE
Send email on-behalf of subuser using @sendgrid/mail

### ISSUE THREAD

**Issue by nikolajnyboe** [sendgrid/sendgrid-nodejs#1149] opened 2020-06-19 08:31 UTC
Hi,

I have run into the same problem as #886 (Send by subuser). 

Specifically I'm having trouble sending an email "on-behalf" of a subuser using the "Web API V3" and `@sendgrid/mail`.

I have tried with multiple approaches such as:

```
const sendGrid = require("@sendgrid/mail");
const message = {
  headers: {
    Authorization: `Token ${process.env.SENDGRID_TOKEN}`,
    "On-Behalf-Of": "subuser_username"
  },
  to: email.to,
  from: email.from,
  templateId: email.templateId,
  dynamic_template_data: {
    ...dynamicData,
  },
  attachments: attachments,
}
sendGrid.send(message)
```

But none of them seem to work.

The only way I have been able to send an email as a subuser, using a dynamic template created on that subusers account, has been by calling `sendGrid.setApiKey("SUBUSER_API_KEY")` just before sending the email.

Am I missing something? - I can't find any documentation on this topic besides #886.

Thank you!

**Comment by thinkingserious** [comment] 2020-06-22 22:26
Hello @nikolajnyboe,

[Here is some documentation](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/USAGE.md#on-behalf-of-subusers) that may help. Or, you can set it directly with [this function](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/classes/client.js#L70). ([example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/client.spec.js#L99))

Please let me know if that helps.

Thanks!

With best regards,

Elmer

**Comment by nikolajnyboe** [comment] 2020-07-01 09:14
Hi @thinkingserious,

Thank you for your help!

Unfortunately, I couldn't get it to work. Note, I'm using the `@sendgrid/mail` package. 

Both the example regarding setting the `On-Behalf-Of` header and calling `setImpersonateSubuser()` seems to be using `@sendgrid/client`.

So I tried using `@sendgrid/client` instead but couldn't get it to work anyway 🤷‍♂️

Heres the code for reference:

```
const client = require("@sendgrid/client");
const request = {};

const emailMessage = {
  personalizations: [
    {
      to: [
        {
          email: emai.to.email,
          name: email.to.name,
        },
      ],
      dynamic_template_data: {
        ...
      },
    },
  ],
  from: {
    email: email.from.email,
    name: email.from.name,
  },
  template_id: email.templateId,
  attachments: attachments,
};

request.body = emailMessage;
request.method = "POST";
request.url = "/v3/mail/send";

client.setImpersonateSubuser("subuser_username");
client.request(request).then(([response, body]) => {
  console.log(response.statusCode);
  console.log(response.body);
});
```
I get a 202 response but the email doesn't get sent.

I need to get to get something working, so I think I need to use the approach where I'm calling `sendGrid.setApiKey("SUBUSER_API_KEY")` before sending the email, until I find a better solution.

Thank you again for your time! 🙂

Btw, I found [this page](https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/on-behalf-of) in the docs, stating that "The on-behalf-of header does not work with the mail.send API". I don't know if that's the problem, but I just wanted to point it out.

**Comment by thinkingserious** [comment] 2020-07-02 22:32
Thank you for the detailed response!

Indeed, the `mail/send` endpoint does not support the `on-behalf-of` header. I believe you are using a correct solution, calling `sendGrid.setApiKey("SUBUSER_API_KEY")` before sending the email. Since you have a working solution and the issue is not related to this library, I'll close this one out. Please let us know if you run into further issues.

**Closed by thinkingserious** 2020-07-02 22:32 UTC
Labels: status: waiting for feedback, type: question

**Comment by tomascortes** [comment] 2021-11-03 14:56
is possible to have a fully automated way to add subusers and then using `sendGrid.setApiKey("SUBUSER_API_KEY")` send email from them?
