### ISSUE TITLE
sendgrid node client uses three different casing conventions

### ISSUE THREAD

**Issue by mikemaccana** [sendgrid/sendgrid-nodejs#223] opened 2016-04-13 19:30 UTC
From the README:

    var params = {
      fromname: '',
      replyto:  '',
      files: [
        {
          contentType:  '',           // optional        
        }
      ],
      file_data:  {}
    };

As you can see above, sendgrid uses three different casing conventions: totallylower, snake_case and camelCase.

This is a breaking change, but the next major version should just use camelCase and SNAKE_CASE_FOR_CONSTS like the JavaScript stdlib does.

**Comment by thinkingserious** [comment] 2016-04-13 20:17
Hello Mike,

Thanks for the feedback!

I'm currently in the process of rewriting this library, and I'm talking care to follow Node.js conventions. You can already give the new HTTP Client a spin: https://github.com/sendgrid/nodejs-http-client

I've been consulting with [Felix's guide](https://github.com/felixge/node-style-guide) and using [ESLint](http://eslint.org).

I'm going to close this one, since this will no longer be an issue.

Thanks again!

Elmer

**Closed by thinkingserious** 2016-04-13 20:17 UTC

**Comment by mikemaccana** [comment] 2016-04-13 20:22
Cheers Elmer and thanks for the fast response! I gather the next version of this module uses nodejs-http-client to do the heavy lifting, right? 

Do you know when the next version of this library will be out or beta-able? I'd love to test if it's cool.

**Comment by thinkingserious** [comment] 2016-04-13 20:27
Cheers @mikemaccana!

Yes, that client will serve as the engine (it was designed to be generic so the community could use it for other APIs also, I just happened to use SendGrid as the example :), whereas the `sendgrid-nodejs` library will make things easy to interact with SendGrid specifically. 

You can get an idea where we're heading by checking out the recently re-released Python library: https://github.com/sendgrid/sendgrid-python. From there we'll be adding helper functions to implement common workflows.

We don't think it we be longer than a few more months before we release it and yes, we'll have a limited beta before then that I'd love to have you participate in. Just email us at DX at sendgrid.

For now, if you have any feedback on the new Node.js client, please let us know. 

Thanks for your support and welcome to the 'Grid!

With Best Regards,

Elmer
