### ISSUE TITLE
New release 6.4.0 not compatible with node 6.X - cannot send template emails

### ISSUE THREAD

**Issue by shaibt** [sendgrid/sendgrid-nodejs#933] opened 2019-05-18 14:40 UTC
#### Issue Summary

Using email templates causes this error in node 6 env - and emails cannot be sent:

Object.values is not a function
    at Mail.setDynamicTemplateData (/app/node_modules/@sendgrid/helpers/classes/mail.js:342:12)
    at Mail.fromData (/app/node_modules/@sendgrid/helpers/classes/mail.js:91:12)
    at new Mail (/app/node_modules/@sendgrid/helpers/classes/mail.js:44:12)
    at Function.create (/app/node_modules/@sendgrid/helpers/classes/mail.js:627:12)
    at MailService.send (/app/node_modules/@sendgrid/mail/src/classes/mail-service.js:174:25)

This is indeed an expected error as Object.values isn't supported in node 6.

#### Steps to Reproduce

Send an email with _templateId_ and _dynamic_template_data_ that is a JS object.

#### Technical details:

* sendgrid-nodejs Version: 6.4.0
* Node.js Version: 6.14.4

**Comment by shaibt** [comment] 2019-05-18 15:23
Also, reverting back to version 6.3.1 doesn't help as nom package 6.3.1 still pulls in helper functions from 6.40 (!?) which contain the non-compatible code:

┬ @sendgrid/mail@6.3.
│ ├── **@sendgrid/client@6.4.0**
│ └─┬ **@sendgrid/helpers@6.4.0**
│   ├─┬ chalk@2.4.2
│   │ ├─┬ ansi-styles@3.2.1
│   │ │ └─┬ color-convert@1.9.3
│   │ │   └── color-name@1.1.3
│   │ ├── escape-string-regexp@1.0.5
│   │ └─┬ supports-color@5.5.0
│   │   └── has-flag@3.0.0
│   └── deepmerge@2.2.1

**Comment by thinkingserious** [comment] 2019-05-21 00:04
Hello @shaibt,

It looks like this issue is a duplicate of https://github.com/sendgrid/sendgrid-nodejs/issues/929. Please follow that issue for progress. Also, I just posted a band aid solution there that may help. 

With Best Regards,

Elmer

@jennapederson,

If you can please upvote the other issue (#929) that will help it gain traction in our backlog. Thanks!

**Comment by jbistis** [comment] 2019-09-01 13:46
Elmer, what is the band-aid solution?

**Closed** 2020-03-03 20:00 UTC
Labels: status: duplicate

**Comment by childish-sambino** [comment] 2020-03-03 20:02
@jbistis This was the suggested band-aid: https://github.com/facebook/jest/issues/3687#issuecomment-325373305
