### ISSUE TITLE
Intermittent 401 - Unauthorized

### ISSUE THREAD

**Issue by YM-KA** [sendgrid/sendgrid-nodejs#1008] opened 2019-12-19 13:58 UTC
#### Issue Summary

Most of the time I can send mail via the API with no problem, but sometimes I get error "401 unauthorized". The execution before and after will succeed using the same credentials in a hourly scheduled google cloud function. 

#### Steps to Reproduce

1. const sgMail = require('@sendgrid/mail')
2. sgMail.setApiKey(firebaseFunctionsConfig.sendgridapikey)
2. Compose message object
3. sgMail.send(message)

Error message for last error event 2019-12-18T16:00:07.306245987Z:
```
textPayload: "sendEmail error { Error: Unauthorized
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 401,
  message: 'Unauthorized',
  response: 
   { headers: 
      { server: 'nginx',
        date: 'Wed, 18 Dec 2019 16:00:02 GMT',
        'content-type': 'application/json',
        'content-length': '74',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Array] } } }"  
```

Same execution triggered again manually at 2019-12-19T13:24:54.265888495Z worked with no errors. 

Kind regards /K

#### Technical details:

* sendgrid-nodejs Version: master 6.4.0
* Node.js Version: 8.11.1

**Comment by bnazaruk** [comment] 2019-12-27 21:21
Encountered a very similar error. Can be solved by hardcoding the api keys in the code.

But you don't wanna do it. 

The way readme suggest doing it is:
```echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env```

It's not a good way cuz it workd only for this session. You can just put your keys in the bash profile for them to be globally available. refresh the console after that.

Sendgrid folks, update your readme please. This question was asked at least three times here and you did nothing to stop the issue.

**Comment by YoomiAB** [comment] 2019-12-28 10:53
Thanks @bnazaruk for the spreading some light on the issue!
When testing out the package I had the key hardcoded, that worked fine. 

I then had the keys imported via ".env" files and [dotenv](https://github.com/motdotla/dotenv) and finally via [firebase enviroment config](https://firebase.google.com/docs/functions/config-env). 
Both dotenv and firebase config seemed to experience issues. I could print the keys to console, but still got a 401 error. 

I have now shifted to clean rest calls to the API using [axios](https://github.com/axios/axios), ditching the sendgrid-nodejs package entirely. Seems to work flawlessly so far.

**Comment by fosteradorkor** [comment] 2019-12-29 01:43
I'm having the same issue with the package. It was working fine a couple of months ago

**Comment by bnazaruk** [comment] 2019-12-30 04:45
ye, I see a lot of people ditching the "library" and going with a generic rest client. The "library" itself is, basically, just a small rest client. It doesn't really do much. I expected it to be more like, say, Jira library that hides the complexity of the api from you. You just treat it as a local class.

They should probably mention in the read me that this "library" is generally just a generic rest client.

**Comment by pratiknikam** [comment] 2020-02-21 18:56
I'm having exact same issue. Hardcoding a key works but doesn't work when you are using it from `.env` or through constant.

**Comment by childish-sambino** [comment] 2020-02-24 17:22
Closing as duplicate of #970 

See my [comment](https://github.com/sendgrid/sendgrid-nodejs/issues/970#issuecomment-590447667) there to follow-up.

**Closed by childish-sambino** 2020-02-24 17:22 UTC
